# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('pedagogie', 'Pédagogie'), ('technique', 'Technique'), ('marketing', 'Marketing'), ('operations', 'Opérations'), ('qualite', 'Qualité'), ('support', 'Support'), ('design', 'Design'), ('facturation', 'Facturation')], default='general', max_length=20)),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='non_lu', max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Information'), ('succes', 'Succès'), ('avertissement', 'Avertissement'), ('erreur', 'Erreur'), ('urgence', 'Urgence')], default='info', max_length=15)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lien', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
