# Generated by Django 6.0.6 on 2026-06-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Module',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('metier', models.CharField(choices=[('pilote_de_ligne', 'Pilote de ligne'), ('personnel_navigant', 'Personnel Navigant Commercial'), ('ingenieur_aeronautique', 'Ingénieur aéronautique'), ('controleur_aerien', 'Contrôleur aérien'), ('technicien_aeronautique', 'Technicien aéronautique'), ('mecanicien_avion', 'Mécanicien avion'), ('agent_escale', "Agent d'escale"), ('formation_avancee', 'Formation avancée')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parcours/')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('gratuit', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('duree_estimee', models.IntegerField(default=0, help_text='Durée en heures')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('qcm_simple', 'QCM simple'), ('qcm_multiple', 'QCM multiple'), ('vrai_faux', 'Vrai/Faux'), ('texte_trous', 'Texte à trous'), ('reorganisation', 'Réorganisation')], default='qcm_simple', max_length=20)),
                ('texte', models.TextField()),
                ('reponse_texte', models.CharField(blank=True, max_length=500)),
                ('explication', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('position_correcte', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Réponse',
                'ordering': ['position_correcte'],
            },
        ),
        migrations.CreateModel(
            name='CoursItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('test', 'Test')], max_length=10)),
                ('numero', models.IntegerField()),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('duree_estimee', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('actif', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parcours.moduleparcours')),
            ],
            options={
                'verbose_name': 'Cours/Test',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='moduleparcours',
            name='parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='parcours.parcours'),
        ),
        migrations.CreateModel(
            name='ProgressionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termine', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('tentatives', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcours.coursitem')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcours.moduleparcours')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours.parcours')),
            ],
            options={
                'verbose_name': 'Progression utilisateur',
            },
        ),
    ]
