# Generated by Django 6.0.6 on 2026-06-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionutilisateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='parcours.coursitem'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='parcours.question'),
        ),
        migrations.AlterUniqueTogether(
            name='coursitem',
            unique_together={('module', 'type', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleparcours',
            unique_together={('parcours', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionutilisateur',
            unique_together={('user', 'parcours', 'module', 'item')},
        ),
    ]
