# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('rapport', 'Rapport'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(upload_to='vault/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('taille', models.IntegerField(default=0)),
                ('est_confidentiel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document (Vault)',
                'verbose_name_plural': 'Documents (Vault)',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='PageStatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_page', models.CharField(choices=[('a_propos', 'À propos'), ('mentions_legales', 'Mentions légales'), ('cgu', "Conditions Générales d'Utilisation"), ('confidentialite', 'Politique de confidentialité'), ('cookies', 'Politique de cookies'), ('accessibilite', 'Accessibilité')], max_length=30, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par_dg', models.BooleanField(default=False)),
                ('approuve_par_coordinateurs', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page statique',
                'verbose_name_plural': 'Pages statiques',
                'ordering': ['type_page'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Ventoryx Academy', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('couleur_primaire', models.CharField(default='#0F1C2E', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#0077B6', max_length=7)),
                ('couleur_accent', models.CharField(default='#FF6B35', max_length=7)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('description_site', models.TextField(blank=True)),
                ('mots_cles', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
