# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', "En cours d'examen"), ('retenue', 'Retenue'), ('rejetee', 'Rejetée')], default='soumise', max_length=15)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('notes_recruteur', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('parcours', models.CharField(max_length=200)),
                ('hash_verification', models.CharField(max_length=64, unique=True)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('revoke', 'Révoqué')], default='valide', max_length=10)),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificat',
                'ordering': ['-date_delivrance'],
            },
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('type_contrat', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('archivee', 'Archivée')], default='brouillon', max_length=10)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
    ]
