# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('contenu', models.TextField()),
                ('resume', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('vues', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('mots_cles', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['nom'],
            },
        ),
    ]
