# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plateforme', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('reseaux_sociaux', 'Réseaux sociaux'), ('push', 'Push notification')], default='email', max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifiee', 'Planifiée'), ('active', 'Active'), ('terminee', 'Terminée')], default='brouillon', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campagne',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('departement', models.CharField(choices=[('pedagogie', 'Pédagogie'), ('technique', 'Technique'), ('marketing', 'Marketing'), ('operations', 'Opérations'), ('qualite', 'Qualité'), ('support', 'Support'), ('design', 'Design')], max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('critique', 'Critique')], default='normale', max_length=10)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tâche',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket support',
                'ordering': ['-date_creation'],
            },
        ),
    ]
