# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('inscription', 'Inscription'), ('modification_profil', 'Modification profil'), ('changement_mdp', 'Changement mot de passe'), ('reset_mdp', 'Réinitialisation mot de passe'), ('paiement', 'Paiement'), ('acces_vault', 'Accès vault'), ('chatbot', 'Chatbot'), ('chatbot_bloque', 'Chatbot bloqué'), ('chatbot_reponse_bloquee', 'Chatbot réponse bloquée'), ('module_cree', 'Module créé'), ('cours_cree', 'Cours créé'), ('quiz_cree', 'Quiz créé'), ('question_ajoutee', 'Question ajoutée'), ('tache_cree', 'Tâche créée'), ('bug_signale', 'Bug signalé'), ('campagne_cree', 'Campagne créée'), ('article_cree', 'Article créé'), ('ticket_cree', 'Ticket créé'), ('maquette_cree', 'Maquette créée'), ('composant_cree', 'Composant créé'), ('export_messages', 'Export messages'), ('export_candidatures', 'Export candidatures'), ('rapport_hebdo', 'Rapport hebdomadaire'), ('message_coordinateurs', 'Message coordinateurs'), ('archivage_messages', 'Archivage messages'), ('audit_departement', 'Audit département'), ('audit_lance', 'Audit lancé'), ('validation_budget', 'Validation budget'), ('formation_planifiee', 'Formation planifiée'), ('partenaire_ajoute', 'Partenaire ajouté'), ('innovation_proposee', 'Innovation proposée'), ('nc_signalée', 'Non-conformité signalée'), ('chat_envoye', 'Chat envoyé'), ('message_repondu', 'Message répondu'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('gravite', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=20)),
                ('objet', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
