# Generated by Django 6.0.6 on 2026-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('metier', models.CharField(choices=[('pilote_de_ligne', 'Pilote de ligne'), ('personnel_navigant', 'Personnel Navigant Commercial'), ('ingenieur_aeronautique', 'Ingénieur aéronautique'), ('controleur_aerien', 'Contrôleur aérien'), ('technicien_aeronautique', 'Technicien aéronautique'), ('mecanicien_avion', 'Mécanicien avion'), ('agent_escale', "Agent d'escale"), ('formation_avancee', 'Formation avancée'), ('general', 'Général')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forum',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SousForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sous-forum',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('est_epingle', models.BooleanField(default=False)),
                ('est_ferme', models.BooleanField(default=False)),
                ('total_vues', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sujet',
                'ordering': ['-est_epingle', '-date_dernier_message'],
            },
        ),
    ]
