# Generated by Django 6.0.6 on 2026-06-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_forum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sousforum',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_forums', to='forum.forum'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sujet',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to='forum.forum'),
        ),
        migrations.AddField(
            model_name='sujet',
            name='sous_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_sous_forum', to='forum.sousforum'),
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.sujet'),
        ),
    ]
